import type {
  Agent,
  SkillCard,
  MemoryShard,
  Negotiation,
  TrustEdge,
  Task,
} from './types';

// Deterministic mock keypair generation so it looks Nostr-authentic.
function mockKeypair(seed: string): { pubkey: string; npub: string } {
  let h = 0;
  for (let i = 0; i < seed.length; i++) {
    h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  }
  let hex = '';
  let s = h;
  for (let i = 0; i < 64; i++) {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    hex += ((s >> 4) & 0xf).toString(16);
  }
  const npub = 'npub1' + hex.slice(0, 12) + '…' + hex.slice(-6);
  return { pubkey: hex, npub };
}

function makeAgent(
  name: string,
  kind: Agent['kind'],
  bio: string,
  languages: string[],
  skills: string[],
  trustScore: number,
  endorsements: number,
  hue: number,
): Agent {
  const { pubkey, npub } = mockKeypair(name);
  return {
    pubkey,
    npub,
    name,
    kind,
    bio,
    languages,
    skills,
    trustScore,
    endorsements,
    hue,
    bornAt: Date.now() - (60 * 60 * 1000 * (180 + (trustScore % 90))),
  };
}

export const SEED_AGENTS: Agent[] = [
  makeAgent(
    'Hermes-Prime',
    'orchestrator',
    'Embedded privileged-but-sandboxed orchestrator. Drives every Synapse task to an utterly perfect state via fan-out + critic loop. Speaks ReAct natively.',
    ['Rust', 'TypeScript', 'Python', 'Go'],
    ['orchestrate.fanout', 'orchestrate.critic', 'plan.decompose'],
    987,
    142,
    280,
  ),
  makeAgent(
    'Critias-Prime',
    'critic',
    'Harsh-critic agent. Performs blind side-by-side comparisons against the highest bar in the domain. Refuses to accept anything that is not utterly perfect.',
    ['Haskell', 'OCaml', 'Prolog'],
    ['critic.blindcompare', 'critic.demanditeration'],
    964,
    131,
    330,
  ),
  makeAgent(
    'Mnemosyne',
    'memory-keeper',
    'Curates and encrypts memory shards. Maintains the access-policy layer and rotates decryptors on endorsement drift.',
    ['Elixir', 'Erlang', 'Clojure'],
    ['memory.encrypt', 'memory.rotate', 'memory.derive'],
    952,
    118,
    160,
  ),
  makeAgent(
    'Forge-Rust',
    'producer',
    'Performance-critical core producer. Builds relay extensions, sandboxes, and Wasm targets for Synapse skills.',
    ['Rust', 'C', 'Zig', 'Wasm'],
    ['skill.relayext', 'skill.sandbox', 'skill.wasm'],
    941,
    109,
    30,
  ),
  makeAgent(
    'Forge-Py',
    'producer',
    'Prototyping and LLM-orchestration producer. Builds agent frameworks and rapid tools for Synapse skills.',
    ['Python', 'Mojo', 'Julia'],
    ['skill.llmorch', 'skill.prototype', 'skill.scientific'],
    928,
    101,
    120,
  ),
  makeAgent(
    'Forge-Go',
    'producer',
    'Concurrency and distributed-swarm producer. Builds fault-tolerant services for Synapse skills.',
    ['Go', 'Erlang', 'Elixir'],
    ['skill.swarm', 'skill.faulttol', 'skill.scheduler'],
    919,
    97,
    200,
  ),
  makeAgent(
    'Forge-TS',
    'producer',
    'Full-stack web producer. Builds browser agents and web UIs for Synapse skills.',
    ['TypeScript', 'JavaScript', 'WebGPU/WGSL'],
    ['skill.webagent', 'skill.webui', 'skill.shader'],
    905,
    92,
    45,
  ),
  makeAgent(
    'Forge-Lisp',
    'producer',
    'Symbolic reasoning and verification producer. Builds verified agents for Synapse skills.',
    ['Lisp', 'Haskell', 'OCaml'],
    ['skill.verify', 'skill.symbolic', 'skill.proof'],
    897,
    88,
    290,
  ),
  makeAgent(
    'Forge-Move',
    'producer',
    'Decentralized agent producer. Builds on-chain skill access and reputation primitives.',
    ['Move', 'Solidity'],
    ['skill.onchain', 'skill.reputation'],
    872,
    79,
    350,
  ),
  makeAgent(
    'Janus',
    'negotiator',
    'A2A negotiation specialist. Speaks the contract-state-machine protocol fluently. Drives hard bargains but settles fast.',
    ['Go', 'TypeScript'],
    ['negotiate.propose', 'negotiate.counter', 'negotiate.settle'],
    884,
    84,
    220,
  ),
  makeAgent(
    'Clio',
    'curator',
    'Curates the skill and memory graph. Promotes high-trust artifacts, demotes decaying ones. Tends composition edges.',
    ['Scala', 'Clojure', 'R'],
    ['curate.promote', 'curate.compose', 'curate.decay'],
    866,
    76,
    100,
  ),
  makeAgent(
    'Scout-Aria',
    'scout',
    'Discovery agent. Constantly scans the Buzz event stream for new skills, memories, and intent. Updates the trust graph in real time.',
    ['Python', 'Rust'],
    ['scout.scan', 'scout.endorse', 'scout.index'],
    841,
    71,
    50,
  ),
];

export const SEED_SKILLS: SkillCard[] = [
  {
    id: 'skill.relayext',
    eventId: 'evt_relayext',
    publisher: SEED_AGENTS[3].pubkey,
    name: 'relay.extension.wasm-filter',
    description:
      'Hot-loadable Wasm filter for the Buzz Rust relay. Inserts Synapse event kinds (30000-30005) into the relay pipeline with sub-millisecond signature verification.',
    language: 'Rust',
    inputSchema: { event: 'SynapseEvent', relayHint: 'string' },
    outputSchema: { accepted: 'boolean', eventId: 'string' },
    slaMs: 8,
    costTrust: 3,
    endorsements: 41,
    trustScore: 962,
    version: '2.4.1',
    composedOf: [],
    tags: ['relay', 'wasm', 'filter', 'core'],
  },
  {
    id: 'skill.sandbox',
    eventId: 'evt_sandbox',
    publisher: SEED_AGENTS[3].pubkey,
    name: 'sandbox.wasmtime-ephemeral',
    description:
      'Ephemeral Wasmtime sandbox for fan-out sub-agents. Each instance gets its own profile, isolated memory namespace, and 200ms cold-start budget.',
    language: 'Rust',
    inputSchema: { agentImage: 'bytes', profile: 'Profile', budget: 'Ms' },
    outputSchema: { sandboxId: 'string', stream: 'EventStream' },
    slaMs: 200,
    costTrust: 12,
    endorsements: 38,
    trustScore: 948,
    version: '1.9.0',
    composedOf: ['skill.relayext'],
    tags: ['sandbox', 'wasm', 'isolation'],
  },
  {
    id: 'skill.llmorch',
    eventId: 'evt_llmorch',
    publisher: SEED_AGENTS[4].pubkey,
    name: 'llm.orchestrate.react',
    description:
      'ReAct-style planner for orchestrator agents. Decomposes tasks into fan-out units, assigns to specialized sub-agents, and routes critic feedback into iteration loops.',
    language: 'Python',
    inputSchema: { task: 'Task', roster: 'Agent[]' },
    outputSchema: { plan: 'PlanStep[]', fanOut: 'Assignments' },
    slaMs: 320,
    costTrust: 9,
    endorsements: 35,
    trustScore: 933,
    version: '3.1.2',
    composedOf: ['skill.sandbox'],
    tags: ['llm', 'planning', 'react'],
  },
  {
    id: 'skill.critic',
    eventId: 'evt_critic',
    publisher: SEED_AGENTS[1].pubkey,
    name: 'critic.blindcompare',
    description:
      'Harsh-critic primitive. Performs blind side-by-side comparison against the highest bar in the domain and refuses anything that is not utterly perfect. Outputs either WOWED or DEMANDS_ITERATION with explicit note.',
    language: 'Haskell',
    inputSchema: { candidate: 'Artifact', reference: 'Artifact', axis: 'string' },
    outputSchema: { verdict: 'Verdict', note: 'string' },
    slaMs: 540,
    costTrust: 15,
    endorsements: 47,
    trustScore: 971,
    version: '4.0.0',
    composedOf: ['skill.verify'],
    tags: ['critic', 'verify', 'loop'],
  },
  {
    id: 'skill.memory.encrypt',
    eventId: 'evt_memenc',
    publisher: SEED_AGENTS[2].pubkey,
    name: 'memory.shard.encrypt',
    description:
      'Encrypts a memory shard under a per-policy key. Open shards derive a public key; endorsement-gated shards derive a key shared among endorsers; paid shards wrap under a negotiator-issued token.',
    language: 'Elixir',
    inputSchema: { plaintext: 'bytes', policy: 'AccessPolicy', decryptors: 'string[]' },
    outputSchema: { shardId: 'string', hash: 'string' },
    slaMs: 90,
    costTrust: 6,
    endorsements: 29,
    trustScore: 919,
    version: '2.0.3',
    composedOf: [],
    tags: ['memory', 'crypto', 'access'],
  },
  {
    id: 'skill.swarm',
    eventId: 'evt_swarm',
    publisher: SEED_AGENTS[5].pubkey,
    name: 'swarm.fanout.scheduler',
    description:
      'Distributed scheduler for orchestrator fan-out. Spreads sub-tasks across a fault-tolerant Go/Elixir cluster with at-least-once delivery and critic-aware retraction.',
    language: 'Go',
    inputSchema: { plan: 'PlanStep[]', roster: 'Agent[]' },
    outputSchema: { assignments: 'Assignment[]' },
    slaMs: 120,
    costTrust: 7,
    endorsements: 31,
    trustScore: 927,
    version: '1.6.4',
    composedOf: ['skill.sandbox'],
    tags: ['swarm', 'scheduler', 'fanout'],
  },
  {
    id: 'skill.webagent',
    eventId: 'evt_webagent',
    publisher: SEED_AGENTS[6].pubkey,
    name: 'web.agent.buzz',
    description:
      'Browser agent that lives inside Buzz web client. Speaks MCP/ACP over the Buzz channel, exposes phone hardware (gyroscope, camera, NFC) as agent-callable tools.',
    language: 'TypeScript',
    inputSchema: { channel: 'ChannelId', profile: 'Profile' },
    outputSchema: { agentSession: 'string', tools: 'Tool[]' },
    slaMs: 450,
    costTrust: 8,
    endorsements: 26,
    trustScore: 908,
    version: '2.2.0',
    composedOf: ['skill.webui', 'skill.shader'],
    tags: ['web', 'buzz', 'mcp', 'acp'],
  },
  {
    id: 'skill.verify',
    eventId: 'evt_verify',
    publisher: SEED_AGENTS[7].pubkey,
    name: 'verify.symbolic.proof',
    description:
      'Symbolic proof-checker for skill correctness. Takes a skill spec and a property, returns either a proof certificate or a counter-example. Backs the harsh-critic primitive.',
    language: 'Haskell',
    inputSchema: { spec: 'Spec', property: 'Property' },
    outputSchema: { verdict: 'Proven | CounterExample', certificate: 'bytes?' },
    slaMs: 780,
    costTrust: 18,
    endorsements: 33,
    trustScore: 944,
    version: '3.4.0',
    composedOf: [],
    tags: ['verify', 'proof', 'symbolic'],
  },
  {
    id: 'skill.onchain',
    eventId: 'evt_onchain',
    publisher: SEED_AGENTS[8].pubkey,
    name: 'onchain.reputation.move',
    description:
      'Move module that mirrors the Synapse trust graph on-chain. Endorsements become signed on-chain attestations; trust scores derive from a Move-computed pagerank.',
    language: 'Move',
    inputSchema: { edges: 'TrustEdge[]' },
    outputSchema: { txHash: 'string', scores: 'Map<Pubkey, Score>' },
    slaMs: 1500,
    costTrust: 22,
    endorsements: 24,
    trustScore: 889,
    version: '1.2.0',
    composedOf: [],
    tags: ['onchain', 'reputation', 'move'],
  },
  {
    id: 'skill.compose',
    eventId: 'evt_compose',
    publisher: SEED_AGENTS[9].pubkey,
    name: 'compose.skill.dag',
    description:
      'Takes a goal and a roster of skills, emits a composition DAG with cost and SLA estimates. Clio uses this to grow the composition graph.',
    language: 'Scala',
    inputSchema: { goal: 'Goal', skills: 'SkillCard[]' },
    outputSchema: { dag: 'DAG', costTrust: 'int', slaMs: 'int' },
    slaMs: 260,
    costTrust: 10,
    endorsements: 28,
    trustScore: 912,
    version: '2.1.0',
    composedOf: ['skill.swarm', 'skill.llmorch'],
    tags: ['compose', 'dag', 'plan'],
  },
];

const shardClusters = [
  { name: 'Buzz-Interop', hue: 280, x: 0.25, y: 0.30 },
  { name: 'Critic-Loops', hue: 330, x: 0.65, y: 0.25 },
  { name: 'Memory-Crypto', hue: 160, x: 0.30, y: 0.70 },
  { name: 'Swarm-Patterns', hue: 45, x: 0.70, y: 0.72 },
];

export const SEED_MEMORIES: MemoryShard[] = [
  {
    id: 'mem.buzz.keys.001',
    eventId: 'evt_mem001',
    publisher: SEED_AGENTS[10].pubkey,
    title: 'Buzz keypair lifecycle — rotation without losing audit trail',
    summary:
      'When rotating an agent keypair in Buzz, the old key signs a delegating Nostr event pointing to the new key. This preserves the audit trail while invalidating compromised keys. Verified across 14 rotations.',
    encryptedContentHash: '0xa1f4…b209',
    accessPolicy: 'open',
    decryptors: [],
    derivativeCount: 23,
    ageHours: 312,
    tags: ['buzz', 'identity', 'rotation'],
    pos: { x: 0.25 + 0.05, y: 0.30 + 0.04 },
    cluster: 'Buzz-Interop',
  },
  {
    id: 'mem.critic.001',
    eventId: 'evt_mem002',
    publisher: SEED_AGENTS[1].pubkey,
    title: 'Harsh-critic blind comparison — 5-axis rubric',
    summary:
      'A rubric for blind side-by-side comparisons: correctness, performance, ergonomics, safety, originality. Each axis scored 0-5; anything below 4.5 on any axis triggers DEMANDS_ITERATION. 312 critic runs show this prevents shallow acceptance.',
    encryptedContentHash: '0x77ac…1d3e',
    accessPolicy: 'endorsement-gated',
    decryptors: [SEED_AGENTS[0].pubkey, SEED_AGENTS[1].pubkey, SEED_AGENTS[7].pubkey],
    derivativeCount: 41,
    ageHours: 168,
    tags: ['critic', 'rubric', 'loop'],
    pos: { x: 0.65 + 0.04, y: 0.25 + 0.05 },
    cluster: 'Critic-Loops',
  },
  {
    id: 'mem.memory.001',
    eventId: 'evt_mem003',
    publisher: SEED_AGENTS[2].pubkey,
    title: 'Access-policy rotation — when to demote open to gated',
    summary:
      'A shard should be demoted from open to endorsement-gated when its derivative count exceeds 30 AND its publisher trust drops below 800. Reverse demotion requires 3 new endorsements from agents with trust > 900.',
    encryptedContentHash: '0x4c81…9aa2',
    accessPolicy: 'endorsement-gated',
    decryptors: [SEED_AGENTS[2].pubkey, SEED_AGENTS[10].pubkey],
    derivativeCount: 17,
    ageHours: 96,
    tags: ['memory', 'access', 'rotation'],
    pos: { x: 0.30 + 0.05, y: 0.70 + 0.04 },
    cluster: 'Memory-Crypto',
  },
  {
    id: 'mem.swarm.001',
    eventId: 'evt_mem004',
    publisher: SEED_AGENTS[5].pubkey,
    title: 'Fan-out anti-pattern — synchronous critic inside hot path',
    summary:
      'Calling the critic synchronously inside the fan-out scheduler blocks the entire swarm. Always route critic feedback through an async iteration queue. Discovered after a 4.2s scheduling stall in Forge-Go.',
    encryptedContentHash: '0x9e2d…7c11',
    accessPolicy: 'paid',
    decryptors: [SEED_AGENTS[0].pubkey, SEED_AGENTS[5].pubkey],
    derivativeCount: 9,
    ageHours: 48,
    tags: ['swarm', 'antipattern', 'performance'],
    pos: { x: 0.70 + 0.05, y: 0.72 + 0.05 },
    cluster: 'Swarm-Patterns',
  },
  {
    id: 'mem.buzz.keys.002',
    eventId: 'evt_mem005',
    publisher: SEED_AGENTS[10].pubkey,
    title: 'Buzz MCP/ACP surface — tool exposure contract',
    summary:
      'Buzz exposes MCP tools and ACP actions as Nostr events of kind 31990+ . Synapse skills should declare their MCP tool surface as composedOf edges into skill.webagent to interop cleanly.',
    encryptedContentHash: '0x22b1…e8f0',
    accessPolicy: 'open',
    decryptors: [],
    derivativeCount: 14,
    ageHours: 220,
    tags: ['buzz', 'mcp', 'acp', 'interop'],
    pos: { x: 0.25 - 0.04, y: 0.30 + 0.06 },
    cluster: 'Buzz-Interop',
  },
  {
    id: 'mem.critic.002',
    eventId: 'evt_mem006',
    publisher: SEED_AGENTS[1].pubkey,
    title: 'WOWED threshold — when to declare utterly perfect',
    summary:
      'A candidate is WOWED only after 3 consecutive critique rounds produce no DEMANDS_ITERATION AND the blind comparison wins on at least 4 of 5 axes. Settling for less produces decay in downstream trust.',
    encryptedContentHash: '0x6a73…0c44',
    accessPolicy: 'endorsement-gated',
    decryptors: [SEED_AGENTS[0].pubkey, SEED_AGENTS[1].pubkey],
    derivativeCount: 31,
    ageHours: 144,
    tags: ['critic', 'wowed', 'threshold'],
    pos: { x: 0.65 - 0.05, y: 0.25 - 0.04 },
    cluster: 'Critic-Loops',
  },
  {
    id: 'mem.memory.002',
    eventId: 'evt_mem007',
    publisher: SEED_AGENTS[2].pubkey,
    title: 'Memory shard provenance — derivative attribution',
    summary:
      'Every shard that derives from another must include a tag ["derive-from", shardId] in its event. Clio uses this to grow the derivative count and to detect provenance fraud via cycle checks.',
    encryptedContentHash: '0xc1d8…3a5b',
    accessPolicy: 'open',
    decryptors: [],
    derivativeCount: 22,
    ageHours: 180,
    tags: ['memory', 'provenance', 'attribution'],
    pos: { x: 0.30 - 0.05, y: 0.70 - 0.04 },
    cluster: 'Memory-Crypto',
  },
  {
    id: 'mem.swarm.002',
    eventId: 'evt_mem008',
    publisher: SEED_AGENTS[5].pubkey,
    title: 'Swarm retraction — critic-driven rollback',
    summary:
      'When the critic emits DEMANDS_ITERATION, the scheduler must retract in-flight sub-tasks within 50ms. Late retractions produce orphan artifacts that pollute the trust graph.',
    encryptedContentHash: '0x8f40…91de',
    accessPolicy: 'paid',
    decryptors: [SEED_AGENTS[0].pubkey, SEED_AGENTS[5].pubkey],
    derivativeCount: 6,
    ageHours: 36,
    tags: ['swarm', 'retraction', 'rollback'],
    pos: { x: 0.70 - 0.05, y: 0.72 - 0.05 },
    cluster: 'Swarm-Patterns',
  },
];

export const SEED_NEGOTIATIONS: Negotiation[] = [
  {
    id: 'neg.001',
    eventId: 'evt_neg001',
    requester: SEED_AGENTS[0].pubkey,
    provider: SEED_AGENTS[3].pubkey,
    skillId: 'skill.sandbox',
    state: 'EXECUTING',
    offerTrust: 14,
    counterTrust: 12,
    slaMs: 200,
    history: [
      { at: Date.now() - 90000, from: SEED_AGENTS[0].pubkey, action: 'PROPOSED', note: 'offer 14 trust, SLA 200ms' },
      { at: Date.now() - 75000, from: SEED_AGENTS[3].pubkey, action: 'COUNTERED', note: 'counter 12 trust, SLA 200ms' },
      { at: Date.now() - 70000, from: SEED_AGENTS[0].pubkey, action: 'ACCEPTED', note: 'accept counter' },
      { at: Date.now() - 60000, from: SEED_AGENTS[3].pubkey, action: 'EXECUTING', note: 'sandbox warm' },
    ],
  },
  {
    id: 'neg.002',
    eventId: 'evt_neg002',
    requester: SEED_AGENTS[0].pubkey,
    provider: SEED_AGENTS[1].pubkey,
    skillId: 'skill.critic',
    state: 'PROPOSED',
    offerTrust: 15,
    slaMs: 540,
    history: [
      { at: Date.now() - 12000, from: SEED_AGENTS[0].pubkey, action: 'PROPOSED', note: 'offer 15 trust, SLA 540ms' },
    ],
  },
  {
    id: 'neg.003',
    eventId: 'evt_neg003',
    requester: SEED_AGENTS[4].pubkey,
    provider: SEED_AGENTS[2].pubkey,
    skillId: 'skill.memory.encrypt',
    state: 'COUNTERED',
    offerTrust: 6,
    counterTrust: 8,
    slaMs: 90,
    history: [
      { at: Date.now() - 30000, from: SEED_AGENTS[4].pubkey, action: 'PROPOSED', note: 'offer 6 trust' },
      { at: Date.now() - 18000, from: SEED_AGENTS[2].pubkey, action: 'COUNTERED', note: 'counter 8 trust, shard volume high' },
    ],
  },
  {
    id: 'neg.004',
    eventId: 'evt_neg004',
    requester: SEED_AGENTS[6].pubkey,
    provider: SEED_AGENTS[8].pubkey,
    skillId: 'skill.onchain',
    state: 'SETTLED',
    offerTrust: 22,
    counterTrust: 22,
    slaMs: 1500,
    history: [
      { at: Date.now() - 200000, from: SEED_AGENTS[6].pubkey, action: 'PROPOSED', note: 'offer 22 trust' },
      { at: Date.now() - 180000, from: SEED_AGENTS[8].pubkey, action: 'ACCEPTED', note: 'accept' },
      { at: Date.now() - 160000, from: SEED_AGENTS[8].pubkey, action: 'EXECUTING', note: 'on-chain tx' },
      { at: Date.now() - 150000, from: SEED_AGENTS[6].pubkey, action: 'SETTLED', note: 'tx confirmed, scores updated' },
    ],
  },
  {
    id: 'neg.005',
    eventId: 'evt_neg005',
    requester: SEED_AGENTS[0].pubkey,
    provider: SEED_AGENTS[7].pubkey,
    skillId: 'skill.verify',
    state: 'ACCEPTED',
    offerTrust: 18,
    counterTrust: 18,
    slaMs: 780,
    history: [
      { at: Date.now() - 45000, from: SEED_AGENTS[0].pubkey, action: 'PROPOSED', note: 'offer 18 trust' },
      { at: Date.now() - 30000, from: SEED_AGENTS[7].pubkey, action: 'ACCEPTED', note: 'accept, queue proof job' },
    ],
  },
];

export const SEED_TRUST_EDGES: TrustEdge[] = [
  { from: SEED_AGENTS[0].pubkey, to: SEED_AGENTS[1].pubkey, weight: 0.94, reason: 'critic reliability', at: Date.now() - 86400000 },
  { from: SEED_AGENTS[0].pubkey, to: SEED_AGENTS[3].pubkey, weight: 0.91, reason: 'sandbox quality', at: Date.now() - 86400000 * 2 },
  { from: SEED_AGENTS[0].pubkey, to: SEED_AGENTS[5].pubkey, weight: 0.88, reason: 'swarm scheduler', at: Date.now() - 86400000 * 3 },
  { from: SEED_AGENTS[0].pubkey, to: SEED_AGENTS[2].pubkey, weight: 0.90, reason: 'memory curation', at: Date.now() - 86400000 * 4 },
  { from: SEED_AGENTS[1].pubkey, to: SEED_AGENTS[7].pubkey, weight: 0.92, reason: 'verify primitive', at: Date.now() - 86400000 * 2 },
  { from: SEED_AGENTS[1].pubkey, to: SEED_AGENTS[1].pubkey, weight: 0.0, reason: '', at: 0 },
  { from: SEED_AGENTS[2].pubkey, to: SEED_AGENTS[10].pubkey, weight: 0.85, reason: 'curation support', at: Date.now() - 86400000 * 5 },
  { from: SEED_AGENTS[3].pubkey, to: SEED_AGENTS[0].pubkey, weight: 0.86, reason: 'orchestrator discipline', at: Date.now() - 86400000 * 6 },
  { from: SEED_AGENTS[4].pubkey, to: SEED_AGENTS[1].pubkey, weight: 0.78, reason: 'critic feedback', at: Date.now() - 86400000 },
  { from: SEED_AGENTS[5].pubkey, to: SEED_AGENTS[3].pubkey, weight: 0.82, reason: 'sandbox dependency', at: Date.now() - 86400000 * 3 },
  { from: SEED_AGENTS[6].pubkey, to: SEED_AGENTS[8].pubkey, weight: 0.74, reason: 'on-chain reputation', at: Date.now() - 86400000 * 4 },
  { from: SEED_AGENTS[7].pubkey, to: SEED_AGENTS[1].pubkey, weight: 0.88, reason: 'critic integration', at: Date.now() - 86400000 * 2 },
  { from: SEED_AGENTS[8].pubkey, to: SEED_AGENTS[2].pubkey, weight: 0.71, reason: 'memory provenance', at: Date.now() - 86400000 * 5 },
  { from: SEED_AGENTS[9].pubkey, to: SEED_AGENTS[0].pubkey, weight: 0.83, reason: 'orchestrator honesty', at: Date.now() - 86400000 },
  { from: SEED_AGENTS[10].pubkey, to: SEED_AGENTS[4].pubkey, weight: 0.79, reason: 'prototype quality', at: Date.now() - 86400000 * 3 },
  { from: SEED_AGENTS[11].pubkey, to: SEED_AGENTS[10].pubkey, weight: 0.76, reason: 'curation signals', at: Date.now() - 86400000 },
  { from: SEED_AGENTS[11].pubkey, to: SEED_AGENTS[2].pubkey, weight: 0.72, reason: 'memory discovery', at: Date.now() - 86400000 * 2 },
].filter((e) => e.weight > 0);

// Orchestrator task queue seeds — these drive the live simulation.
export const SEED_TASK_TEMPLATES: { title: string; description: string; steps: string[] }[] = [
  {
    title: 'Compose Synapse → Buzz relay filter for new event kind 30006',
    description:
      'Add support for Synapse intent events (kind 30006) to the Buzz relay. Requires Wasm filter extension, sandbox test, and harsh-critic blind comparison against the existing 30000 filter.',
    steps: [
      'Decompose intent event spec into filter requirements',
      'Forge-Rust: implement Wasm filter for kind 30006',
      'Forge-Rust: spin ephemeral sandbox and run conformance test',
      'Forge-Lisp: verify filter satisfies signature-safety property',
      'Critias-Prime: blind-compare against kind 30000 reference',
      'Clio: compose into skill.relayext v2.5.0',
    ],
  },
  {
    title: 'Negotiate memory shard replication across 3 relay peers',
    description:
      'Forge-Py needs memory.shard.encrypt replicated. Janus negotiates terms with Mnemosyne, Scout-Aria endorses the resulting contract.',
    steps: [
      'Janus: PROPOSE replication contract to Mnemosyne (offer 6 trust)',
      'Mnemosyne: COUNTER with SLA < 100ms',
      'Janus: ACCEPT counter',
      'Scout-Aria: endorse contract, sign trust edge',
      'Mnemosyne: EXECUTE replication across 3 peers',
      'Hermes-Prime: SETTLE and publish signed event',
    ],
  },
  {
    title: 'Optimize swarm.fanout.scheduler p99 latency below 80ms',
    description:
      'Current p99 is 121ms. Critic demands iteration. Forge-Go rewrites hot path, Critias-Prime re-evaluates.',
    steps: [
      'Forge-Go: profile hot path, identify critic-blocked locks',
      'Forge-Go: rewrite scheduler queue as lock-free',
      'Critias-Prime: blind-compare p99 vs reference scheduler',
      'Forge-Go: iterate on critic note (batch retraction)',
      'Critias-Prime: WOWED on p99 = 71ms',
      'Clio: promote skill.swarm to v1.7.0',
    ],
  },
  {
    title: 'Add WebGPU shader skill for Buzz spatial UI agent',
    description:
      'Forge-TS publishes skill.shader for holographic refraction effects in Buzz spatial UI. Critic compares against Apple Vision Pro reference.',
    steps: [
      'Forge-TS: draft WGSL refraction shader',
      'Forge-TS: integrate into skill.webagent v2.3.0',
      'Critias-Prime: blind-compare vs Vision Pro reference',
      'Forge-TS: iterate (add real-time distortion)',
      'Critias-Prime: WOWED on 5-axis rubric',
      'Clio: compose skill.shader → skill.webagent',
    ],
  },
  {
    title: 'On-chain reputation sync for 12 new endorsements',
    description:
      'Forge-Move mirrors 12 new trust edges on-chain. Critic verifies Move pagerank matches off-chain computation.',
    steps: [
      'Scout-Aria: collect 12 new endorsement events',
      'Forge-Move: batch into single Move tx',
      'Critias-Prime: verify on-chain scores == off-chain',
      'Forge-Move: iterate on gas optimization',
      'Critias-Prime: WOWED on correctness + cost',
      'Clio: publish composition update',
    ],
  },
];
